services:
  spatial-server:
    build: .
    command: >
      flask --app spatial_server/server run --host 0.0.0.0
      --port 8001 --cert=/ssl/cert.pem --key=/ssl/key.pem
    # command: tail -F anything
    volumes:
      - ./:/code
    ports:
      - 8001:8001
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
