services:
  spatial-server:
    build: .
    command: bash start_server.sh
    volumes:
      - ./:/code
    ports:
      - 8001:8001 # Flask server
      - 8888:8888 # Jupyter notebook
    ipc: host
    shm_size: 20g
    environment:
      - TORCH_HOME=/code/data/torch_hub
      - BEHIND_PROXY=${BEHIND_PROXY:-false}
      - HTTPS=${HTTPS:-true} # Default is HTTPS
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
